LABELS_EL010 = [
    "Hip21",
    "Hip22",
    "Hip23",
    "Hip24",
    "Hip25",
    "Hip26",
    "Hip27",
    "Hip28",
    "Hip29",
    "Hip210",
    "Temp1",
    "Temp2",
    "Temp3",
    "Temp4",
    "Temp5",
    "Temp6",
    "Temp7",
    "Temp8",
    "Temp9",
    "Temp10",
    "FrOr1",
    "FrOr2",
    "FrOr3",
    "FrOr4",
    "FrOr5",
    "FrOr6",
    "FrOr7",
    "FrOr8",
    "FrOr9",
    "FrOr10",
    "FrOr11",
    "FrOr12",
    "In An1",
    "In An2",
    "In An3",
    "In An4",
    "In An5",
    "In An6",
    "In An7",
    "In An8",
    "In An9",
    "In An10",
    "In An11",
    "In An12",
    "InPo1",
    "InPo2",
    "InPo3",
    "InPo4",
    "InPo5",
    "InPo6",
    "InPo7",
    "InPo8",
    "InPo9",
    "InPo10",
    "InPo11",
    "InPo12",
    "Hip11",
    "Hip12",
    "Hip13",
    "Hip14",
    "Hip15",
    "Hip16",
    "Hip17",
    "Hip18",
    "Hip19",
    "Hip110",
    "Hip111",
    "Hip112",
]

DATASET_PATHS_EL010 = [
    "/traces/raw/Hip21",
    "/traces/raw/Hip22",
    "/traces/raw/Hip23",
    "/traces/raw/Hip24",
    "/traces/raw/Hip25",
    "/traces/raw/Hip26",
    "/traces/raw/Hip27",
    "/traces/raw/Hip28",
    "/traces/raw/Hip29",
    "/traces/raw/Hip210",
    "/traces/raw/Temp1",
    "/traces/raw/Temp2",
    "/traces/raw/Temp3",
    "/traces/raw/Temp4",
    "/traces/raw/Temp5",
    "/traces/raw/Temp6",
    "/traces/raw/Temp7",
    "/traces/raw/Temp8",
    "/traces/raw/Temp9",
    "/traces/raw/Temp10",
    "/traces/raw/FrOr1",
    "/traces/raw/FrOr2",
    "/traces/raw/FrOr3",
    "/traces/raw/FrOr4",
    "/traces/raw/FrOr5",
    "/traces/raw/FrOr6",
    "/traces/raw/FrOr7",
    "/traces/raw/FrOr8",
    "/traces/raw/FrOr9",
    "/traces/raw/FrOr10",
    "/traces/raw/FrOr11",
    "/traces/raw/FrOr12",
    "/traces/raw/In An1",
    "/traces/raw/In An2",
    "/traces/raw/In An3",
    "/traces/raw/In An4",
    "/traces/raw/In An5",
    "/traces/raw/In An6",
    "/traces/raw/In An7",
    "/traces/raw/In An8",
    "/traces/raw/In An9",
    "/traces/raw/In An10",
    "/traces/raw/In An11",
    "/traces/raw/In An12",
    "/traces/raw/InPo1",
    "/traces/raw/InPo2",
    "/traces/raw/InPo3",
    "/traces/raw/InPo4",
    "/traces/raw/InPo5",
    "/traces/raw/InPo6",
    "/traces/raw/InPo7",
    "/traces/raw/InPo8",
    "/traces/raw/InPo9",
    "/traces/raw/InPo10",
    "/traces/raw/InPo11",
    "/traces/raw/InPo12",
    "/traces/raw/Hip11",
    "/traces/raw/Hip12",
    "/traces/raw/Hip13",
    "/traces/raw/Hip14",
    "/traces/raw/Hip15",
    "/traces/raw/Hip16",
    "/traces/raw/Hip17",
    "/traces/raw/Hip18",
    "/traces/raw/Hip19",
    "/traces/raw/Hip110",
    "/traces/raw/Hip111",
    "/traces/raw/Hip112",
]

LEAD_PREFIXES_EL010 = ["Hip2", "Temp", "FrOr", "In An", "InPo", "Hip1"]

DATASET_PATHS_SZ2 = [
    "/traces/raw/Hip1",
    "/traces/raw/Hip2",
    "/traces/raw/Hip3",
    "/traces/raw/Hip4",
    "/traces/raw/Hip5",
    "/traces/raw/Hip6",
    "/traces/raw/Hip7",
    "/traces/raw/Hip8",
    "/traces/raw/Hip9",
    "/traces/raw/Hip10",
    "/traces/raw/Hip11",
    "/traces/raw/Hip12",
    "/traces/raw/aHip1",
    "/traces/raw/aHip2",
    "/traces/raw/aHip3",
    "/traces/raw/aHip4",
    "/traces/raw/aHip5",
    "/traces/raw/aHip6",
    "/traces/raw/aHip7",
    "/traces/raw/aHip8",
    "/traces/raw/aHip9",
    "/traces/raw/aHip10",
    "/traces/raw/aHip11",
    "/traces/raw/aHip12",
]

LEAD_PREFIXES_SZ2 = ["Hip", "aHip"]

LEAD_PREFIXES_AJ = ["Amy", "HippA", "LesA", "LesI", "LesP", "LesS", "HippM", "T1Ant"]

DATASET_PATHS_008 = [
    "/traces/raw/AL1",
    "/traces/raw/AL2",
    "/traces/raw/AL3",
    "/traces/raw/AL4",
    "/traces/raw/AL5",
    "/traces/raw/AL6",
    "/traces/raw/AL7",
    "/traces/raw/AL8",
    "/traces/raw/AL9",
    "/traces/raw/AL10",
    "/traces/raw/AL11",
    "/traces/raw/AL12",
    "/traces/raw/aHL1",
    "/traces/raw/aHL2",
    "/traces/raw/aHL3",
    "/traces/raw/aHL4",
    "/traces/raw/aHL5",
    "/traces/raw/aHL6",
    "/traces/raw/aHL7",
    "/traces/raw/aHL8",
    "/traces/raw/aHL9",
    "/traces/raw/aHL10",
    "/traces/raw/aHL11",
    "/traces/raw/aHL12",
    "/traces/raw/OFR1",
    "/traces/raw/OFR2",
    "/traces/raw/OFR3",
    "/traces/raw/OFR4",
    "/traces/raw/OFR5",
    "/traces/raw/OFR6",
    "/traces/raw/OFR7",
    "/traces/raw/OFR8",
    "/traces/raw/OFR9",
    "/traces/raw/OFR10",
    "/traces/raw/OFR11",
    "/traces/raw/OFR12",
    "/traces/raw/OFR13",
    "/traces/raw/OFR14",
    "/traces/raw/OFR15",
    "/traces/raw/CingR1",
    "/traces/raw/CingR2",
    "/traces/raw/CingR9",
    "/traces/raw/CingR10",
    "/traces/raw/CingR11",
    "/traces/raw/CingR12",
    "/traces/raw/AR1",
    "/traces/raw/AR2",
    "/traces/raw/AR3",
    "/traces/raw/AR4",
    "/traces/raw/AR6",
    "/traces/raw/AR7",
    "/traces/raw/AR8",
    "/traces/raw/AR9",
    "/traces/raw/AR10",
    "/traces/raw/AR11",
    "/traces/raw/AR12",
    "/traces/raw/aHR1",
    "/traces/raw/aHR2",
    "/traces/raw/aHR3",
    "/traces/raw/aHR4",
    "/traces/raw/aHR5",
    "/traces/raw/aHR6",
    "/traces/raw/aHR7",
    "/traces/raw/aHR8",
    "/traces/raw/aHR9",
    "/traces/raw/aHR10",
    "/traces/raw/aHR11",
    "/traces/raw/aHR12",
    "/traces/raw/EntR1",
    "/traces/raw/EntR2",
    "/traces/raw/EntR3",
    "/traces/raw/EntR4",
    "/traces/raw/EntR5",
    "/traces/raw/EntR6",
    "/traces/raw/EntR7",
    "/traces/raw/EntR8",
    "/traces/raw/EntR9",
    "/traces/raw/EntR10",
    "/traces/raw/pHR1",
    "/traces/raw/pHR2",
    "/traces/raw/pHR3",
    "/traces/raw/pHR4",
    "/traces/raw/pHR5",
    "/traces/raw/pHR6",
    "/traces/raw/pHR7",
    "/traces/raw/pHR8",
    "/traces/raw/pHR9",
    "/traces/raw/pHR10",
    "/traces/raw/pHR11",
    "/traces/raw/pHR12",
    "/traces/raw/aIR1",
    "/traces/raw/aIR2",
    "/traces/raw/aIR3",
    "/traces/raw/aIR4",
    "/traces/raw/aIR5",
    "/traces/raw/aIR6",
    "/traces/raw/aIR7",
    "/traces/raw/aIR8",
    "/traces/raw/aIR9",
    "/traces/raw/aIR10",
    "/traces/raw/aIR11",
    "/traces/raw/aIR12",
    "/traces/raw/aIR13",
    "/traces/raw/aIR14",
    "/traces/raw/aIR15",
    "/traces/raw/aIR16",
    "/traces/raw/aIR17",
    "/traces/raw/aIR18",
    "/traces/raw/pIR1",
    "/traces/raw/pIR3",
    "/traces/raw/pIR4",
    "/traces/raw/pIR5",
    "/traces/raw/pIR6",
    "/traces/raw/pIR7",
    "/traces/raw/pIR8",
    "/traces/raw/pIR9",
    "/traces/raw/pIR10",
    "/traces/raw/pIR11",
    "/traces/raw/pIR12",
    "/traces/raw/pIR13",
    "/traces/raw/pIR14",
    "/traces/raw/pIR15",
    "/traces/raw/pIR16",
    "/traces/raw/pIR17",
]
LEAD_PREFIXES_008 = [
    "AL",
    "aHL",
    "OFR",
    "CingR",
    "AR",
    "aHR",
    "EntR",
    "pHR",
    "aIR",
    "pIR",
]
